// <auto-generated />
namespace RecruitmentQUIZ.Migrations.RecruitClassMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class UpdateUserWithDateDemarrageExam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateUserWithDateDemarrageExam));
        
        string IMigrationMetadata.Id
        {
            get { return "202005081601102_UpdateUserWithDateDemarrageExam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
